#!/bin/bash

# 🧪 Webhook Test Samples - Use estes comandos para testar a webhook-unificada
# Replace email and IDs with your test data

WEBHOOK_URL="https://lkhfbhvamnqgcqlrriaw.supabase.co/functions/v1/webhook-unificada"
TEST_EMAIL="teste@webhook.test"

echo "🚀 Webhook Test Samples"
echo "======================="
echo ""
echo "Escolha um teste para rodar:"
echo "1) Vega Test"
echo "2) GGCheckout Test"
echo "3) AmploPay Test"
echo ""

# ============================================
# TESTE 1: VEGA
# ============================================
echo "📋 Test 1: VEGA Webhook"
echo "Copie e execute no seu terminal:"
echo ""
echo "curl -X POST $WEBHOOK_URL \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"customer\": {"
echo "      \"email\": \"$TEST_EMAIL\","
echo "      \"name\": \"Testador Vega\""
echo "    },"
echo "    \"items\": ["
echo "      {"
echo "        \"code\": \"3MGN9O\","
echo "        \"title\": \"EdukaPapers - Papercrafts de Natal\","
echo "        \"amount\": 2999"
echo "      }"
echo "    ],"
echo "    \"total_price\": 2999,"
echo "    \"status\": \"approved\","
echo "    \"transaction_token\": \"tx_vega_$(date +%s)\","
echo "    \"method\": \"pix\""
echo "  }'"
echo ""
echo "---"
echo ""

# ============================================
# TESTE 2: GGCHECKOUT
# ============================================
echo "📋 Test 2: GGCHECKOUT Webhook"
echo "Copie e execute no seu terminal:"
echo ""
echo "curl -X POST $WEBHOOK_URL \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"customer\": {"
echo "      \"email\": \"$TEST_EMAIL\","
echo "      \"name\": \"Testador GGCheckout\""
echo "    },"
echo "    \"products\": ["
echo "      {"
echo "        \"id\": \"WpjID8aV49ShaQ07ABzP\","
echo "        \"name\": \"Eduka Prime - Plano Evoluir\","
echo "        \"price\": 10000"
echo "      }"
echo "    ],"
echo "    \"payment\": {"
echo "      \"method\": \"credit_card\","
echo "      \"amount\": 10000"
echo "    },"
echo "    \"event\": \"card.paid\","
echo "    \"status\": \"paid\","
echo "    \"id\": \"tx_gg_$(date +%s)\""
echo "  }'"
echo ""
echo "---"
echo ""

# ============================================
# TESTE 3: AMPLOPAY
# ============================================
echo "📋 Test 3: AMPLOPAY Webhook"
echo "Copie e execute no seu terminal:"
echo ""
echo "curl -X POST $WEBHOOK_URL \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"customer\": {"
echo "      \"email\": \"$TEST_EMAIL\","
echo "      \"name\": \"Testador AmploPay\""
echo "    },"
echo "    \"product_id\": \"prod_amplo_123\","
echo "    \"product_name\": \"Eduka Prime - Acesso Vitalício\","
echo "    \"amount\": 29999,"
echo "    \"status\": \"approved\","
echo "    \"id\": \"tx_amplo_$(date +%s)\","
echo "    \"payment_method\": \"bank_transfer\""
echo "  }'"
echo ""
echo "---"
echo ""

echo "📌 IMPORTANTE:"
echo "1. Substitua 'teste@webhook.test' pelo email de um usuário real no seu banco"
echo "2. Substitua os IDs de produto pelos IDs reais que você configurou em plans_v2"
echo "3. Após rodar, verifique:"
echo "   - webhook_logs (status deve ser 'success')"
echo "   - user_subscriptions (deve ter subscription ativa)"
echo "   - users (plano_ativo deve estar preenchido)"
echo ""
